INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100000, "start_date", "end_date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100000, "start_date", "end_date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100000, "start_date", "end_date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100000, "start_date", "end_date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100000, "start_date", "end_date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100000, "start_date", "end_date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100000, "start_date", "end_date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100000, "start_date", "end_date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100000, "start_date", "end_date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100000, "start_date", "end_date");

INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);
INSERT INTO users (name, age) VALUES ("name", 30);

INSERT INTO pledges (amount, user_id, project_id) values (100000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 12, 2);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 17, 7);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 19, 9);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) values (100000, 10, 10);